// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.GoogleAnalyticsWrapper.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GaTraffic
    {
        /// <summary>
        /// Initializes a new instance of the GaTraffic class.
        /// </summary>
        public GaTraffic()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GaTraffic class.
        /// </summary>
        public GaTraffic(string clientId = default(string), string source = default(string), string medium = default(string), string campaign = default(string), string keyword = default(string), string content = default(string))
        {
            ClientId = clientId;
            Source = source;
            Medium = medium;
            Campaign = campaign;
            Keyword = keyword;
            Content = content;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Source")]
        public string Source { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Medium")]
        public string Medium { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Campaign")]
        public string Campaign { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Keyword")]
        public string Keyword { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Content")]
        public string Content { get; set; }

    }
}
