// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.GoogleAnalyticsWrapper.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TransactionModel
    {
        /// <summary>
        /// Initializes a new instance of the TransactionModel class.
        /// </summary>
        public TransactionModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TransactionModel class.
        /// </summary>
        public TransactionModel(double amount, double fee, string id = default(string), string userId = default(string), string assetId = default(string), string feeAssetId = default(string))
        {
            Id = id;
            UserId = userId;
            Amount = amount;
            AssetId = assetId;
            Fee = fee;
            FeeAssetId = feeAssetId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UserId")]
        public string UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public double Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetId")]
        public string AssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Fee")]
        public double Fee { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FeeAssetId")]
        public string FeeAssetId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
